Repository atlp-rwanda/matadors-medica-back-office, pull requests merged in 2024-07, with the labels that each got.

#14 Fix: Doctor login and registration with supabase authentication
  constants/types/Types.tsx
  ctx/AuthContext.tsx
  hooks/useWithAuth.tsx
  middleware.ts
  package-lock.json
  package.json
  src/app/assets/images/Ellipse.png
  src/app/assets/images/log.png
  src/app/assets/images/sign.png
  src/app/auth/action.ts
  src/app/auth/confirm/route.ts
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/auth/signup/page.tsx
  src/app/components/Input.tsx
  src/app/components/button.tsx
  src/app/components/footer.tsx
  src/app/components/layout.tsx
  src/app/components/navbar.tsx
  src/app/components/search.tsx
  src/app/components/sidebar.tsx
  src/app/dashboard/appointment/page.tsx
  src/app/dashboard/article/page.tsx
  src/app/dashboard/edit-profile/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/error/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/pages/about.tsx
  src/app/pages/contact.tsx
  src/app/pages/index.tsx
  src/app/pages/login.tsx
  src/app/private/page.tsx
  src/app/utils/supabase/client.ts
  src/app/utils/supabase/middleware.ts
  src/app/utils/supabase/server.ts
  utils/supabase/config.tsx
Labels: bug, Need Review

#17 Fix: Prebuild fixes for Top navigation, and linting warnings
  next.config.mjs
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/auth/signup/page.tsx
  src/app/components/layout.tsx
  src/app/components/search.tsx
  src/app/dashboard/appointment/page.tsx
  src/app/dashboard/article/page.tsx
  src/app/dashboard/edit-profile/page.tsx
  src/app/dashboard/page.tsx
  src/app/pages/login.tsx
Labels: bug, Need Review

#18 Feature: doctor notifications
  constants/types/Types.tsx
  ctx/AuthContext.tsx
  ctx/NotificationsContext.tsx
  next.config.mjs
  public/calendar2Icon.svg
  public/calendarIcon.svg
  public/closeIcon.svg
  public/serviceIcon.svg
  public/walletIcon.svg
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/auth/signup/page.tsx
  src/app/components/NotificationListing.tsx
  src/app/components/layout.tsx
  src/app/components/sidebar.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/notifications/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/pages/about.tsx
  src/app/pages/contact.tsx
  src/app/pages/index.tsx
  src/app/pages/login.tsx
Labels: Need Review, Feature

#22 Appointments Integration
  src/app/components/Appdetails.tsx
  src/app/components/AppointmentsTable.tsx
  src/app/components/sidebar.tsx
  src/app/dashboard/appointment/details/page.tsx
  src/app/dashboard/appointment/page.tsx
  src/app/dashboard/page.tsx
  src/app/page.tsx
  src/app/pages/About.tsx
  src/app/pages/Contact.tsx
Labels: Need Review, Feature

#15 Implement Audio Call Functionality for Doctor-Patient Communication
  next.config.mjs
  package-lock.json
  package.json
  public/profile-picture.png
  src/app/assets/images/profile-picture.png
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/auth/signup/page.tsx
  src/app/components/AudioCallUI.tsx
  src/app/components/ParticipantView.tsx
  src/app/components/footer.tsx
  src/app/components/layout.tsx
  src/app/components/navbar.tsx
  src/app/components/sidebar.tsx
  src/app/dashboard/appointment/audiocall/page.tsx
  src/app/dashboard/home/page.tsx
  src/app/pages/index.tsx
  src/app/pages/login.tsx
  src/app/utils/api.ts
  src/app/utils/supabase/supabase copy.ts
  src/app/utils/supabase/supabase.ts
  tsconfig.json
Labels: Feature
